# Generated by Django 4.2.2 on 2023-08-20 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenreAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_id', models.IntegerField(unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('genre', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['genre'],
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_id', models.IntegerField(unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('studio_name', models.CharField(max_length=255, unique=True)),
                ('company_name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['studio_name'],
            },
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_id', models.IntegerField(unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('anime_title', models.CharField(max_length=255)),
                ('anime_score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('airing_time', models.CharField(blank=True, max_length=50)),
                ('api_url', models.CharField(blank=True, max_length=255)),
                ('poster_url', models.CharField(blank=True, max_length=255)),
                ('genre', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='animelist.genreanime')),
                ('studio', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='animelist.studio')),
            ],
            options={
                'ordering': ['anime_title'],
            },
        ),
    ]
