# Generated by Django 4.2.2 on 2023-10-13 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animelist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='studio',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='animelist.studio'),
        ),
    ]
