# Generated by Django 4.2.2 on 2023-10-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animelist', '0003_alter_anime_studio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='mal_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='genreanime',
            name='mal_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studio',
            name='mal_id',
            field=models.IntegerField(),
        ),
    ]
