# Generated by Django 4.2.2 on 2023-10-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animelist', '0004_alter_anime_mal_id_alter_genreanime_mal_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='mal_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='genreanime',
            name='mal_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='studio',
            name='mal_id',
            field=models.IntegerField(unique=True),
        ),
    ]
