# Generated by Django 3.2.18 on 2023-06-06 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230606_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studio',
            options={'ordering': ['studio_name']},
        ),
    ]
